### ISSUE TITLE
Add support for Elastic APM

### ISSUE THREAD

**Issue by sglebs** [sglebs/mswyw#10]

**Comment by sglebs** [comment]
https://www.elastic.co/guide/en/apm/get-started/current/metrics.html

**Comment by sglebs** [comment]
APDEX implemented by hand via scripted field: https://discuss.elastic.co/t/kibana-calculate-apdex-with-value-from-scripted-field/149845/11

**Comment by sglebs** [comment]
Via Kibana calls (Basic Auth)

// SERVICES
http://sre.softplan.com.br/s/apm/api/apm/services?start=2019-10-29T13:31:07.636Z&end=2019-11-29T13:31:07.637Z&uiFilters={"kuery":"transaction.type : \"request\""}

// FOR 1 SERVICE
http://sre.softplan.com.br/s/apm/api/apm/services?start=2019-10-29T13:31:07.636Z&end=2019-11-29T13:31:07.637Z&uiFilters={"kuery":"transaction.type : \"request\" and service.name : \"atos_pgmbox_barueri_homolog_interna\""}

// MEMORY and CPU
http://sre.softplan.com.br/s/apm/api/apm/services/atos_pgmbox_barueri_homolog_interna/metrics/charts?start=2019-10-29T13:31:07.636Z&end=2019-11-29T13:31:07.637Z&agentName=java&uiFilters=

// NUMBER OF ENDPOINTS - ARRAY SIZE
http://sre.softplan.com.br/s/apm/api/apm/services/atos_pgmbox_barueri_homolog_interna/transaction_groups?start=2019-10-29T13:31:07.636Z&end=2019-11-29T13:31:07.637Z&transactionType=request&uiFilters={"kuery":"transaction.type : \"request\""}

APDEX: Unavailable via Kibana calls above

**Comment by andersonsoffa** [comment]
Uuuatt?

Em seg., 6 de jan. de 2020 às 13:40, Marcio Marchini <
notifications@github.com> escreveu:

**Comment by sglebs** [comment]
The ElasticAPM has a Backend for Frontend (BFF) for Kibana dashboards. Our first cut was to use those REST APIs. The comment above is just to document them. It mostly works except for the APDEX workaround - its value can't be fetched via the BFF. Example of result:

Instances:
{'mem': 621992335, 'endpoints': 100, 'apdex': 0, 'cpu': 33.300000000000004, 'rpm': 30.9, 'epm': 0.0, '_lang': 'dotnet', '_appname': 'tj-pessoa-api-master'}

--------------------------------------------------
Started : 2020-01-06 14:21:20.990402
Finished: 2020-01-06 14:21:21.801401
Total: 0:00:00.810999
mswyw score: 0.06575291708033866
--------------------------------------------------

Tomorrow we will talk directly to the ElasticSearch indices instead, hoping to be able to fetch all values, including the APDEX workaround.

**Comment by sglebs** [comment]
Note that we used ElasticSeach indices directly in the scripts at https://github.com/sglebs/kibana-software-metrics. The idea is to do the same - the real work is figuring out what data is where :-)

**Comment by sglebs** [comment]
done in eb96729
