### ISSUE TITLE
Problems aggregating metrics from ElasticAPM of Java (maybe others) language services

### ISSUE THREAD

**Issue by tnsampaio** [sglebs/mswyw#22]
When I try to get the metrics for a ElasticAPM-instrumented Java application, I get this error:

Traceback (most recent call last):
  File "utilities/mswyw.py", line 137, in <module>
    main()
  File "utilities/mswyw.py", line 103, in main
    mswyw_score = compute_formula(arguments.get("--calcProvider"), ms_runtime_data, formula_coefficients, overrides)
  File "utilities/mswyw.py", line 75, in compute_formula
    return calc_module.calc_mswyw(ms_runtime_data, formula_coefficients, overrides, DEFAULT_VALUE_FOR_MISSING_MATRIC)
  File "/Users/tnsampaio/Desenvolvimento/Softplan/mswyw/utilities/formula.py", line 13, in calc_mswyw
    formula_coefficients["cpu"]*overrides.get("cpu", metrics.get("cpu", default_value_for_missing_metric)) + \
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

It seems to be a problem on the filter on Elasticsearch.

The filter actually looks for a field named: "system.process.memory.rss.bytes" which doesn't actually exists in Java metrics (ElasticAPM server version 7.6.2) Not sure about the agent version yet.

**Comment by sglebs** [comment]
fixed in #24
