### ISSUE TITLE
Add score per container

### ISSUE THREAD

**Issue by jesielconceicao** [sglebs/mswyw#27]
Please add mswyw-score's value for each application.
Currently, we have this value for all applications, like the example below:
```json
{
    "..."
    "runtime-data": [
        {
            "mem": 1100000000,
             "..."
            "_appname": "example-app"
        }
    ],
   ## "HERE" ##
   "mswyw-score": 0.06945433646013302
}
```
We would like this information for each application, like the example below:
```json
{
    "..."
    "runtime-data": [
        {
            "mem": 1100000000,
            "..."
            ## "HERE, too" ##
            "mswyw-score": 0.06945433646013302,
            "_appname": "example-app"
        }
    ],
     ## "HERE" ##
    "mswyw-score": 0.06945433646013302
}
```

**Comment by sglebs** [comment]
NOTE: The score could be computed per container (instance) and also for the group of containers (replicas) for the same app/service (what you call API).

**Comment by sglebs** [comment]
I will add the feature per container. There is no grouping feature yet per API name - although it could be added.

**Comment by sglebs** [comment]
If you need grouping of containers per service name, please enter a separate issue. Right now the score is computed for each container (this issue) or for the overall group (old/original feature). Hierarchical support is not implemented yet.
